### ISSUE TITLE
Error on Xcode 9.0 beta 3

### ISSUE THREAD

**Issue by ajacquelin** [tdesert/capture_ios_sim#3]
` ./capture_ios_sim.rb` will freeze the simulator on Xcode 9 beta 3 with this popup:
![screen shot 2017-07-17 at 18 14 09](https://user-images.githubusercontent.com/1488200/28278038-05bf19b6-6b1c-11e7-9bea-83b5f8270269.png)

**Comment by tdesert** [comment]
@ajacquelin This error is due to several Xcode installations on your system.
If you run `sudo xcode-select -switch /Applications/Xcode-beta.app/Contents/Developer` the problem should be fixed.
Can you give it a try and tell me if this solved the issue?

**Comment by ajacquelin** [comment]
Yes you are right, thanks!
